### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by imranismail** [SenecaSystems/relisa#6]
I just listened to the changelog podcast and Chris from Phoenix mentioned about Relisa, was wondering what is the state of the project and what are the milestones for 1.0 release?

**Comment by ndemonner** [comment]
Wow, I never got notifications from Github about this issue--sorry about that. We've moved to using https://github.com/bitwalker/distillery for our release management needs, since it covers everything we wanted Relisa to be able to do in the future. I highly recommend it.

I'll add a note in the README.
